fresh=int(input("enter the number of fresh loaves purchased:")) 
old=int(input("enter the number of day old loaves purchased:")) 
print("\n")
print("Regular Price=%.2f"%regularprice) 
print("Amount of new loaves=%.2f"%fresh1) 
print("Amount of old loaves=%.2f"%old1) 
print("Total Amount=%.2f"%totalamount)
